### ISSUE TITLE
question of aircraft dataset

### ISSUE THREAD

**Issue by judgment404** [sua-choi/CMS#1]
Excuse me, i download the provided weight of aircraft dataset, but the result is

```
Namespace(batch_size=128, num_workers=8, pretrain_path='./models', transform='imagenet', eval_funcs=['v2'], use_ssb_splits=True, model_name='aircraft_p', dataset_name='aircraft', epochs=20, feat_dim=768, num_clusters=None, inductive=False, k=8, alpha=0.5, image_size=224, train_classes=[0, 1, 2, 3, 4, 5, 10, 11, 14, 16, 17, 19, 21, 22, 23, 24, 27, 28, 29, 30, 33, 36, 37, 38, 39, 41, 43, 44, 45, 46, 47, 48, 52, 53, 56, 57, 58, 63, 64, 65, 66, 67, 71, 73, 76, 77, 79, 92, 95, 99], unlabeled_classes=[6, 7, 8, 9, 12, 13, 31, 32, 25, 26, 18, 20, 15, 78, 82, 51, 49, 50, 54, 55, 59, 60, 61, 68, 69, 70, 85, 86, 87, 88, 80, 81, 42, 84, 40, 90, 74, 75, 97, 98, 34, 35, 93, 94, 96, 72, 91, 83, 62, 89], num_labeled_classes=50, num_unlabeled_classes=50)
Using weights from /home/GEN/code/CMS/log/cms/log/aircraft_p/checkpoints/model_best.pt ...
/home/GEN/miniconda3/envs/torch1/lib/python3.10/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
Predicted number of clusters:  92
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 53/53 [00:34<00:00,  1.54it/s]
num clusters 100
Epoch 0, IMS unlabeled train ACC_v2: All 0.5353 | Old 0.6158 | New 0.4951
num clusters 92
Epoch 0, IMS unlabeled train ACC_v2: All 0.5373 | Old 0.6176 | New 0.4972
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 53/53 [00:19<00:00,  2.74it/s]
num clusters 100
Epoch 1, IMS unlabeled train ACC_v2: All 0.5343 | Old 0.6170 | New 0.4930
num clusters 92
Epoch 1, IMS unlabeled train ACC_v2: All 0.5433 | Old 0.5984 | New 0.5157
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 53/53 [00:19<00:00,  2.71it/s]
num clusters 100
Epoch 2, IMS unlabeled train ACC_v2: All 0.5393 | Old 0.6164 | New 0.5007
num clusters 92
Epoch 2, IMS unlabeled train ACC_v2: All 0.5461 | Old 0.5936 | New 0.5223
ACC with GT number of clusters: All 0.5393 | Old 0.6164 | New 0.5007
ACC with predicted number of clusters: All 0.5461 | Old 0.5936 | New 0.5223
```
the number is smaller than README (53 vs. 56).

And I also try to train the model by myself, but the number is also small than paper(CUB 66, SCARS 48, AIRCRAFT 51). I use the default hyperparameters on github, and no change to codes. I think maybe there are something wrong in my experiment, do you have any idea can help me fix the problem? 

I look forward to your response at your earliest convenience.

**Comment by sua-choi** [comment]
Hi,

Thanks for your interest! I've just noticed that the uploaded checkpoint differs from the best one, and it has now been updated. Sorry for the confusion.
Regarding the reproduced experiment, it might be due to the randomness of training or the variance of our validation scheme. We believe that the suggested validation scheme is the proper approach for a fair and realistic scenario, but it might be somewhat unstable compared to using the ground-truth number of classes. 

If you have any further questions, please feel free to ask. Have a great day!

**Comment by wendy26zhang** [comment]
Thank you for your cool work.
I also try to train the model by myself, the number on CUB(66), AIRCRAFT(51) are also small than paper.

> Excuse me, i download the provided weight of aircraft dataset, but the result is
> 
> ```
> Namespace(batch_size=128, num_workers=8, pretrain_path='./models', transform='imagenet', eval_funcs=['v2'], use_ssb_splits=True, model_name='aircraft_p', dataset_name='aircraft', epochs=20, feat_dim=768, num_clusters=None, inductive=False, k=8, alpha=0.5, image_size=224, train_classes=[0, 1, 2, 3, 4, 5, 10, 11, 14, 16, 17, 19, 21, 22, 23, 24, 27, 28, 29, 30, 33, 36, 37, 38, 39, 41, 43, 44, 45, 46, 47, 48, 52, 53, 56, 57, 58, 63, 64, 65, 66, 67, 71, 73, 76, 77, 79, 92, 95, 99], unlabeled_classes=[6, 7, 8, 9, 12, 13, 31, 32, 25, 26, 18, 20, 15, 78, 82, 51, 49, 50, 54, 55, 59, 60, 61, 68, 69, 70, 85, 86, 87, 88, 80, 81, 42, 84, 40, 90, 74, 75, 97, 98, 34, 35, 93, 94, 96, 72, 91, 83, 62, 89], num_labeled_classes=50, num_unlabeled_classes=50)
> Using weights from /home/GEN/code/CMS/log/cms/log/aircraft_p/checkpoints/model_best.pt ...
> /home/GEN/miniconda3/envs/torch1/lib/python3.10/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
>   warnings.warn(
> Predicted number of clusters:  92
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 53/53 [00:34<00:00,  1.54it/s]
> num clusters 100
> Epoch 0, IMS unlabeled train ACC_v2: All 0.5353 | Old 0.6158 | New 0.4951
> num clusters 92
> Epoch 0, IMS unlabeled train ACC_v2: All 0.5373 | Old 0.6176 | New 0.4972
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 53/53 [00:19<00:00,  2.74it/s]
> num clusters 100
> Epoch 1, IMS unlabeled train ACC_v2: All 0.5343 | Old 0.6170 | New 0.4930
> num clusters 92
> Epoch 1, IMS unlabeled train ACC_v2: All 0.5433 | Old 0.5984 | New 0.5157
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 53/53 [00:19<00:00,  2.71it/s]
> num clusters 100
> Epoch 2, IMS unlabeled train ACC_v2: All 0.5393 | Old 0.6164 | New 0.5007
> num clusters 92
> Epoch 2, IMS unlabeled train ACC_v2: All 0.5461 | Old 0.5936 | New 0.5223
> ACC with GT number of clusters: All 0.5393 | Old 0.6164 | New 0.5007
> ACC with predicted number of clusters: All 0.5461 | Old 0.5936 | New 0.5223
> ```
> 
> the number is smaller than README (53 vs. 56).
> 
> And I also try to train the model by myself, but the number is also small than paper(CUB 66, SCARS 48, AIRCRAFT 51). I use the default hyperparameters on github, and no change to codes. I think maybe there are something wrong in my experiment, do you have any idea can help me fix the problem?
> 
> I look forward to your response at your earliest convenience.
